version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      API_SERVER_ADDR: ":3000"
    ports:
    - "3000:3000"